### ISSUE TITLE
Your site contains two sites

### ISSUE THREAD

**Issue by jmcglad** [Xyaneon/Xyaneon.github.io#2]
Accessing your site using http://www.christopherkylehorton.com/ and http://warrioring64.github.io/ lands me at two distinctly different looking sites. I do not think this behavior is in any way intended. It appears as though http://warrioring64.github.io/ leads to an older version of your site while http://www.christopherkylehorton.com/ leads to the current version.

**Comment by Xyaneon** [comment]
I can confirm this. However, while warrioring64.github.io is the canonical URL, the updated one that I am actually using is the www.christopherkylehorton.com one, which points to the former using a CNAME record on Google Domains. I'm not sure what could be done about this, or if any action is even required.

**Comment by jmcglad** [comment]
Perhaps on the  [christopherkylehorton.com](http://www.christopherkylehorton.com/) site you could change the navbar so the text "Christopher Kyle Horton /" links back to [christopherkylehorton.com](http://www.christopherkylehorton.com/) instead of [warrioring64.github.io](http://warrioring64.github.io/). At least then if a user clicks the navbar link instead of using the "Back to main" button on any of the site sub-pages, then they won't accidentally be taken to the main page of your other site [warrioring64.github.io](http://warrioring64.github.io/).

**Comment by Xyaneon** [comment]
Whoops, I'll get that fixed soon. I'm currently finishing up a branch where I'm reorganizing things a bit.

**Comment by Xyaneon** [comment]
Branch merged. Should be fixed now.
